export const articles = [
  {
    id: '1',
    title: 'How to handle state in React. The missing FAQ.',
    author: 'Osmel Mora',
    url: 'https://medium.com/react-ecosystem/how-to-handle-state-in-react-6f2d3cd73a0c',
    excerpt: 'this is excerpt 1 of the articles 1',
    body: 'this is body 1 of the articles 1',
  },
  {
    id: '2',
    title: 'You might not need React Router',
    author: 'Konstantin Tarkus',
    url: 'https://medium.freecodecamp.com/you-might-not-need-react-router-38673620f3d',
    excerpt: 'this is excerpt 2 of the articles 2',
    body: 'this is body 2 of the articles 2',
  },
  {
    id: '3',
    title: 'Mixins Considered Harmful',
    author: 'Dan Abramov',
    url: 'https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html',
    excerpt: 'this is excerpt 3 of the articles 3',
    body: 'this is body 3 of the articles 3',
  },
  {
    id: '4',
    title: 'React Design Principles',
    author: 'Dan Abramov',
    url: 'https://facebook.github.io/react/contributing/design-principles.html',
    excerpt: 'this is excerpt 4 of the articles 4',
    body: 'this is body 4 of the articles 4',
  },
  {
    id: '5',
    title: "Don't use .bind() when passing props",
    author: 'Dave Ceddia',
    url: 'https://daveceddia.com/avoid-bind-when-passing-props/',
    excerpt: 'this is excerpt 5 of the articles 5',
    body: 'this is body 5 of the articles 5',
  },
];
